select * from KHACHHANG
GO
select * from THUOC




CREATE OR REPLACE TRIGGER TAO_ID_NHAN_VIEN
BEFORE INSERT ON NhanVien
FOR EACH ROW
DECLARE
    DEMNV NUMBER;
    ID CHAR(10);
    CHUOISOKHONG VARCHAR(8) := '0';
    I NUMBER := 0;
    DEMID NUMBER;
    LENGTHID NUMBER;
BEGIN
    SELECT COUNT(MANV) INTO DEMNV FROM NhanVien;
    DEMNV := DEMNV + 1;
    LENGTHID := (10 - ((LENGTH(DEMNV) + LENGTH('NV'))));
    WHILE (I < LENGTHID - 1) LOOP
        CHUOISOKHONG := CONCAT(CHUOISOKHONG, '0');
        I := I + 1;
    END LOOP;
    ID := CONCAT('NV', CHUOISOKHONG || DEMNV);
    SELECT COUNT(MANV) INTO DEMID FROM NhanVien WHERE MANV = ID;
    WHILE (DEMID <> 0) LOOP
        DEMNV := DEMNV + 1;
        CHUOISOKHONG := '0';
        I := 0;
        LENGTHID := 10 - ((LENGTH(DEMNV) + LENGTH('NV')));
        WHILE (I < LENGTHID - 1) LOOP
            CHUOISOKHONG := CONCAT(CHUOISOKHONG, '0');
            I := I + 1;
        END LOOP;
        ID := CONCAT('NV', CHUOISOKHONG || DEMNV);
        SELECT COUNT(MANV) INTO DEMID FROM NhanVien WHERE MANV = ID;
    END LOOP;
    :NEW.MANV := ID;
END;